#!/usr/bin/env bash

FIREFOX_SETUP_DIR=/opt/firefox
FIREFOX_DESKTOP_ENTRY_DIR=/usr/share/applications
FIREFOX_BINARY_PATH=/usr/bin/firefox
FIREFOX_ARCH='linux'

if [ `uname -m` == 'x86_64' ]; then
    FIREFOX_ARCH='linux64'
fi

FIREFOX_DOWNLOAD_URL="https://download.mozilla.org/?product=firefox-latest-ssl&os=${FIREFOX_ARCH}&lang=tr"

if [ -e /usr/local/share/firefox-update/ ]; then
    FIREFOX_UPDATE_DIR=/usr/local/share/firefox-update
else
    FIREFOX_UPDATE_DIR=.
fi

copydesktopfile()
{
    rm -rf ${FIREFOX_DESKTOP_ENTRY_DIR}/firefox.desktop
    cp ${FIREFOX_UPDATE_DIR}/firefox.desktop ${FIREFOX_DESKTOP_ENTRY_DIR}/firefox.desktop
    if [ $? != 0 ]; then
        echo Başlatıcı eklenemedi.
    else
        echo Başlatıcı eklendi.
    fi
}

promptdesktopfile()
{
    if [ -e $FIREFOX_DESKTOP_ENTRY_DIR/firefox.desktop ]; then
        echo Başlatıcının olması gereken yerde zaten bir dosya var. "( ${FIREFOX_DESKTOP_ENTRY_DIR}/firefox.desktop )"
        echo -n Üstüne yazmak ister misiniz? [E/h]" "
        read CHOICE
        case $CHOICE in
            [Ee]|'') copydesktopfile ;;
        esac
    else
        copydesktopfile
    fi
}

linkbinary()
{
    rm -rf $FIREFOX_BINARY_PATH
    ln -s $FIREFOX_SETUP_DIR/firefox $FIREFOX_BINARY_PATH
    if [ $? != 0 ]; then
        echo İkili dosya, dosya sistemine linklenemedi.
    else
        echo İkili dosya, dosya sistemine linklendi.
    fi
}

promptbinary()
{
    if [ -e $FIREFOX_BINARY_PATH ]; then
        echo İkili dosyanın olması gerektiği yerde zaten bir dosya var. "( ${FIREFOX_BINARY_PATH} )"
        echo -n Üstüne yazmak ister misiniz? [E/h]" "
        read CHOICE
        case $CHOICE in
            [Ee]|'') linkbinary ;;
        esac
    else
        linkbinary
    fi
}

if [ $EUID != 0 ]; then
    echo Bu betik çalışabilmesi için \"root\" yetkilerine ihtiyaç duyar.
    exit 1
fi

echo Sunucudan en son sürüm kontrol ediliyor...
LASTEST_FIREFOX_VERSION=`curl -s -D - "$FIREFOX_DOWNLOAD_URL" -o /dev/null | grep "Location:"`

if [ $? != 0 ]; then
    echo "Sunucudan son sürüm bilgisi alınamadı. ($FIREFOX_DOWNLOAD_URL)"
    exit 1
fi

LASTEST_FIREFOX_VERSION=`echo $LASTEST_FIREFOX_VERSION | cut -d '/' -f7`
echo En son Firefox sürümü: $LASTEST_FIREFOX_VERSION

LOGNAME=`logname`
CURRENT_FIREFOX_VERSION=`su $LOGNAME -c "${FIREFOX_SETUP_DIR}/firefox -v"`

if [ $? != 0 ]; then
    echo $FIREFOX_SETUP_DIR dizini altında firefox bulunamadı.
    echo -n $FIREFOX_SETUP_DIR dizinine kurmak ister misiniz? [E/h]" "
else
    CURRENT_FIREFOX_VERSION=`echo $CURRENT_FIREFOX_VERSION | cut -d ' ' -f3`
    echo Mevcut Firefox sürümü: $CURRENT_FIREFOX_VERSION

    if [ $LASTEST_FIREFOX_VERSION == $CURRENT_FIREFOX_VERSION ]; then
        echo Tebrikler! En son Firefox sürümünü kullanmaktasınız.
        promptdesktopfile
        promptbinary
        exit 0
    fi

    echo Görünüşe göre eski bir Firefox sürümü kullanmaktasınız.
    echo -n Güncelleme yapmak istediğinizden emin misiniz? [E/h]" "
fi

read CHOICE
case $CHOICE in
    [hH])
        echo Güncelleme yapılmadan çıkıldı.
        exit 0
    ;;
esac

echo En son Firefox sürümü indiriliyor...
wget -O /tmp/firefox.tar.bz2 $FIREFOX_DOWNLOAD_URL

if [ $? != 0 ]; then
    echo "Sunucudan indirme sırasında bir hata oluştu."
    exit 1
fi

echo Arşiv çıkartılıyor...
tar xjf /tmp/firefox.tar.bz2 -C /tmp/

if [ $? != 0 ]; then
    echo "Arşivden çıkarma esnasında bir hata oluştu."
    exit 1
fi

echo Kopyalama işlemleri gerçekleştiriliyor...
rm -rf ${FIREFOX_SETUP_DIR}

if [ $? != 0 ]; then
    echo "Eski Firefox sürümü silinirken bir hata ile karşılaşıldı."
    exit 1
fi

cp -r /tmp/firefox $FIREFOX_SETUP_DIR

if [ $? != 0 ]; then
    echo "Yeni Firefox sürümü kopyalanırken bir hata ile karşılaşıldı."
    exit 1
fi

promptdesktopfile
promptbinary

echo Güncelleme işlemi başarıyla tamamlandı.
exit 0
